/* eslint-disable @next/next/no-page-custom-font */
/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const stats = [
    {
      value: "10k+",
      text: "COMPANIES",
    },
    {
      value: "314",
      text: "TEMPLATES",
    },
    {
      value: "12M+",
      text: "QUERIES",
    },
  ];

  return (
    <div className="py-4 sm:py-0 sm:w-full sm:h-full sm:flex sm:flex-col sm:justify-center">
      <Head>
        <title>Stats Card Component</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Lexend+Deca&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className="mx-8 my-4 rounded-md text-center bg-cardbg relative pb-8 sm:pb-0 sm:flex sm:flex-row-reverse sm:col-span-6 max-w-[375px] sm:max-w-[1220px] ">
        <img
          id="imgheader"
          src="/images/meeting.webp"
          alt="Meeting"
          className="w-full rounded-t-md sm:rounded-r-md sm:rounded-l-none sm:w-1/2"
        />
        <section className="mt-8 px-4 sm:w-1/2 sm:flex sm:flex-col sm:justify-around sm:text-left sm:p-10">
          <h1 className="font-Inter font-bold sm:text-5xl">
            Get <span className="text-accent">insights</span> that help your
            business grow.
          </h1>
          <p className="mt-8 px-4 font-Inter text-lg sm:text-xl font-normal text-mainp">
            Discover the benefits of data analytics and make better decisions
            regarding revenue, customer experience, and overall efficiency.
          </p>
          <div className="mt-8 flex-col sm:flex sm:flex-row sm:w-full sm:justify-between sm:px-4">
            {stats.map((stat, idx) => (
              <div className="flex flex-col mt-8" key={`stat-${idx}`}>
                <span className="text-3xl font-Inter font-bold">{stat.value}</span>
                <span className="text-sm font-Inter mt-2 tracking-widest text-stat">
                  {stat.text}
                </span>
              </div>
            ))}
          </div>
        </section>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
